In [1]:
import numpy as np

In [2]:
#built in function
arr1= np.zeros((3,4))
print(arr1,arr1.shape)
arr2=np.ones((3,3))
print(arr2,arr2.shape)
arr3= np.full((2,5),5)
print(arr3,arr3.shape)
arr4 = np.eye(3) 
print(arr4, arr4.shape)  
arr5 = np.arange(1, 20, 2)
print(arr5, arr5.shape)  
arr6 = np.linspace(0, 10, 5) 
print(arr6, arr6.shape) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)
[[5 5 5 5 5]
 [5 5 5 5 5]] (2, 5)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 1  3  5  7  9 11 13 15 17 19] (10,)
[ 0.   2.5  5.   7.5 10. ] (5,)


In [ ]:
# to change data type
str_arr=np.array([1,2,3,4,5],dtype="U")
print(str_arr)
int_arr=str_arr.astype(np.int64)
print(int_arr)


['1' '2' '3' '4' '5']
[1 2 3 4 5]


In [4]:
#reshaping
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape((2,3))
print(reshaped,reshaped.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [5]:
#indexing
arr = np.array([1, 2, 3, 4, 5])  
print(arr[0])  

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) 
print(arr[0][1]) 
print(arr[1][2]) 
print(arr[3][2])
#fancy indexing
arr=np.array([1,2,3,4,5,6])
idx=[0,2,4]
print(arr[idx])

1
2
6
12
[1 3 5]


In [7]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7])
print(array1[array1>2])
print(array1[array1%2==0])

[3 4 5 6 7]
[2 4 6]


In [9]:
# Sliced List is a COPY  
py_list = [1, 2, 3, 4, 5]  
copy_list = py_list[1:4] 
copy_list[1] = 333  
print(copy_list)  
print(py_list)
# Sliced Array is a VIEW  
np_arr = np.array([1, 2, 3, 4, 5])  
view_arr = np_arr[1:4]  
view_arr[1] = 333 
print(view_arr)  
print(np_arr) 
# Creating a COPY for Array  
copy_arr = np_arr[1:4].copy() 
copy_arr[2] = 444 
print(copy_arr)  
print(np_arr)

[2, 333, 4]
[1, 2, 3, 4, 5]
[  2 333   4]
[  1   2 333   4   5]
[  2 333 444]
[  1   2 333   4   5]


In [13]:
#multidimentional array
arr2D= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))
sum_of_rows=np.sum(arr2D,axis=0)
print(sum_of_rows)
sum_of_columns=np.sum(arr2D,axis=1)
print(sum_of_columns)
#indexing
print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [17]:
#3D array
arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D,arr3D.shape)
#Indexing
print(arr3D[0,1,1])
#Slicing
print(arr3D[:,0,:])
print(arr3D[:,1:2,0:1])
arr3D[:,0,:]=99
print(arr3D)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]
[[[3]]

 [[9]]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [18]:
#validators
arr=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr **2)
print(arr +2)
print(arr+arr2)

[ 1  4  9 16 25]
[3 4 5 6 7]
[ 7  9 11 13 15]


In [3]:
import numpy as np
#normalization
arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
std=np.std(arr)
print((arr-mean)/std)
print(mean)
print(std)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [4]:
#mathematics funtion
arr = np.array([1, 2, 3, 4, 5])  
print(np.sum(arr))  
print(np.prod(arr)) 
print(np.min(arr))  
  
print(np.argmin(arr))
print(np.max(arr))  

print(np.argmax(arr)) 
print(np.mean(arr))  

print(np.median(arr)) 
print(np.std(arr))  
 
print(np.var(arr)) 

15
120
1
0
5
4
3.0
3.0
1.4142135623730951
2.0


In [6]:
#power function
arr = np.array([1, 2, 3, 4, 5])  
print(np.square(arr)) 
print(np.sqrt(arr))  
 
print(np.pow(arr, 3))

print(np.log(arr))  
print(np.log10(arr))  
print(np.log2(arr))  
print(np.exp(arr)) 
print(np.round(2.678))  
print(np.floor(2.678)) 

print(np.trunc(2.678)) 


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [7]:
#unique 
arr = np.array([1, 2, -5, 3, 8, -4, 2, 5]) 
print(np.abs(arr))  
print(np.sort(arr))  
print(np.unique(arr)) 

[1 2 5 3 8 4 2 5]
[-5 -4  1  2  2  3  5  8]
[-5 -4  1  2  3  5  8]
